[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor --flash-size 8mb --partition-table ./partitions.csv --erase-parts otadata"

[env]
ESP_LOG = "INFO"
ESP_DEVICE_TYPE="esp32c6"
ESP_DEVICE_NAME="esp32c6-example"
ESP_DEVICE_VERSION="0.1.1"

WIFI_SSID="BV Public"
WIFI_PSWD="banviencoaaarp"

MQTT_SERVER_NAME = "broker.bluleap.ai"
MQTT_SERVER_PORT = "8883"
MQTT_CLIENT_ID = "9514a033-a92c-4abc-a46f-c3fe1a986c19"
MQTT_USR_NAME = "16b42082-73e1-4bc4-9c50-bb0666fab2b2"
MQTT_USR_PASS = "f57f9bf3-07b3-4ba5-ae1f-bf6f579e346d"

MENDER_CLIENT_URL="https://hosted.mender.io"
MENDER_CLIENT_TENANT_TOKEN="eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW5kZXIudGVuYW50IjoiNjVkODMyYjNkY2I2ODI1YmQ2OWJjZGRmIiwiaXNzIjoiTWVuZGVyIiwic3ViIjoiNjVkODMyYjNkY2I2ODI1YmQ2OWJjZGRmIn0.oPgY1QLpvMlNJzc9_ZVbrNlWpAvqtZXXHWilw6kVZD-0HZQNZGt4nXbvOFrekfbgU7zHfK9N6ovqWffa7MjqFjceEfbpagYASchFcuqRZPBGTc5MBUmF0YZWzvaw0pBYLK5sakUiEVoAvQJsSdy75NcipTlHneaB96y5WoPBdP7fkdRb0UIWBIHi4O5ZFwDYgaP5SJBj9i-akoIvqnTsZjGfATUuqpNIErnE4yPwn0Rf2CgIdrgl2daTZAwFB0lbHC_Xm2IT5LjbODdTvtnJyVfYoIpU0Bn34YoCl538sPbzIsyArIit8D3uQ8aeviUiyXt857dSbSBE6wHV0gsJMxjBQZApFaYIH4FEk7g2PEV5Q3Fo0-TcL6BXrE10u3DDOMZbspLrqozq_eVfWth6aa_5fNlKIoZeesuwd4QJlviwUSRnCBdN2W-Elu8bhKSfRRmLPX5RL6g_BMyrM-wvcV96kFobZy52IZuMIjAex3I3p7gCu4IxWGB1KrxnmJPi"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]

